//REDUX BOOKS ACTIONS
export const GET_BOOKS = "GET_BOOKS";
export const DELETE_BOOK = "DELETE_BOOK";
export const ADD_BOOK = "ADD_BOOK";
export const BOOKS_LOADING = "BOOKS_LOADING";
export const EDIT_BOOK = "EDIT_BOOK";

//REDUX USER ACTIONS
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";

//REDUX AUTH ACTIONS
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

//REDUX ADD USER ACTIONS
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

//REDUX ERROR ACTIONS
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
